name = "earthlift-soil-declaration-hub"
compatibility_date = "2026-06-18"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = "public"

[browser]
binding = "BROWSER"

[[d1_databases]]
binding = "DB"
database_name = "soil-dec-hub"
database_id = "2b8444f4-67d3-4c27-965b-bba9e4d25b70"

[[r2_buckets]]
binding = "REPORTS"
bucket_name = "soil-dec-reports"

[vars]
HUB_VERSION = "2026.06.18.3-urm-cloud"
